





***************** // there's gotta be an xlib function somewhere that returns these things



const char *key_value_to_name(int key)
{***}

int key_name_to_value(const char *name)
{***}


#define LAXKEY_NULL     "NULL"
#define LAXKEY_Shift    "Shift"
#define LAXKEY_Control  "Control"
#define LAXKEY_Esc      "Esc"
#define LAXKEY_Menu     "Menu"
#define LAXKEY_Pause    "Pause"
#define LAXKEY_Alt      "Alt"
#define LAXKEY_Meta     "Meta"
#define LAXKEY_Del      "Del"
#define LAXKEY_Bksp     "Bksp"
#define LAXKEY_Tab      "Tab"
#define LAXKEY_Ins      "Ins"
#define LAXKEY_Home     "Home"
#define LAXKEY_End      "End"
#define LAXKEY_Enter    "Enter"
#define LAXKEY_Pgup     "Pgup"
#define LAXKEY_Pgdown   "Pgdown"
#define LAXKEY_F1       "F1"
#define LAXKEY_F2       "F2"
#define LAXKEY_F3       "F3"
#define LAXKEY_F4       "F4"
#define LAXKEY_F5       "F5"
#define LAXKEY_F6       "F6"
#define LAXKEY_F7       "F7"
#define LAXKEY_F8       "F8"
#define LAXKEY_F9       "F9"
#define LAXKEY_F10      "F10"
#define LAXKEY_F11      "F11"
#define LAXKEY_F12      "F12"
#define LAXKEY_Left     "Left"
#define LAXKEY_Up       "Up"
#define LAXKEY_Down     "Down"
#define LAXKEY_Right    "Right"
#define LAXKEY_Numlock  "Numlock"
#define LAXKEY_Capslock "Capslock"


//The following are basically one for one with XF86XK_* from /usr/include/X11/XF86keysym.h
//They map various special keys found on different keyboards.

/* Backlight controls. */
#define LAXKEY_MonBrightnessUp   "MonBrightnessUp"
#define LAXKEY_MonBrightnessDown "MonBrightnessDown"
#define LAXKEY_KbdLightOnOff     "KbdLightOnOff"
#define LAXKEY_KbdBrightnessUp   "KbdBrightnessUp"
#define LAXKEY_KbdBrightnessDown "KbdBrightnessDown"

/*
 * Keys found on some "Internet" keyboards.
 */
#define LAXKEY_Standby          "Standby"
#define LAXKEY_AudioLowerVolume "AudioLowerVolume"
#define LAXKEY_AudioMute        "AudioMute"
#define LAXKEY_AudioRaiseVolume "AudioRaiseVolume"
#define LAXKEY_AudioPlay        "AudioPlay"
#define LAXKEY_AudioStop        "AudioStop"
#define LAXKEY_AudioPrev        "AudioPrev"
#define LAXKEY_AudioNext        "AudioNext"
#define LAXKEY_HomePage         "HomePage"
#define LAXKEY_Mail             "Mail"
#define LAXKEY_Start            "Start"
#define LAXKEY_Search           "Search"
#define LAXKEY_AudioRecord      "AudioRecord"

/* These are sometimes found on PDA's (e.g. Palm, PocketPC or elsewhere)   */
#define LAXKEY_Calculator       "Calculator"
#define LAXKEY_Memo             "Memo"
#define LAXKEY_ToDoList         "ToDoList"
#define LAXKEY_Calendar         "Calendar"
#define LAXKEY_PowerDown        "PowerDown"
#define LAXKEY_ContrastAdjust   "ContrastAdjust"
#define LAXKEY_RockerUp         "RockerUp"
#define LAXKEY_RockerDown       "RockerDown"
#define LAXKEY_RockerEnter      "RockerEnter"

/* Some more "Internet" keyboard symbols */
#define LAXKEY_Back             "Back"
#define LAXKEY_Forward          "Forward"
#define LAXKEY_Stop             "Stop"
#define LAXKEY_Refresh          "Refresh"
#define LAXKEY_PowerOff         "PowerOff"
#define LAXKEY_WakeUp           "WakeUp"
#define LAXKEY_Eject            "Eject"
#define LAXKEY_ScreenSaver      "ScreenSaver"
#define LAXKEY_WWW              "WWW"
#define LAXKEY_Sleep            "Sleep"
#define LAXKEY_Favorites        "Favorites"
#define LAXKEY_AudioPause       "AudioPause"
#define LAXKEY_AudioMedia       "AudioMedia"
#define LAXKEY_MyComputer       "MyComputer"
#define LAXKEY_VendorHome       "VendorHome"
#define LAXKEY_LightBulb        "LightBulb"
#define LAXKEY_Shop             "Shop"
#define LAXKEY_History          "History"
#define LAXKEY_OpenURL          "OpenURL"
#define LAXKEY_AddFavorite      "AddFavorite"
#define LAXKEY_HotLinks         "HotLinks"
#define LAXKEY_BrightnessAdjust "BrightnessAdjust"
#define LAXKEY_Finance          "Finance"
#define LAXKEY_Community        "Community"
#define LAXKEY_AudioRewind      "AudioRewind"
#define LAXKEY_BackForward      "BackForward"
#define LAXKEY_Launch0          "Launch0"
#define LAXKEY_Launch1          "Launch1"
#define LAXKEY_Launch2          "Launch2"
#define LAXKEY_Launch3          "Launch3"
#define LAXKEY_Launch4          "Launch4"
#define LAXKEY_Launch5          "Launch5"
#define LAXKEY_Launch6          "Launch6"
#define LAXKEY_Launch7          "Launch7"
#define LAXKEY_Launch8          "Launch8"
#define LAXKEY_Launch9          "Launch9"
#define LAXKEY_LaunchA          "LaunchA"
#define LAXKEY_LaunchB          "LaunchB"
#define LAXKEY_LaunchC          "LaunchC"
#define LAXKEY_LaunchD          "LaunchD"
#define LAXKEY_LaunchE          "LaunchE"
#define LAXKEY_LaunchF          "LaunchF"

#define LAXKEY_ApplicationLeft  "ApplicationLeft"
#define LAXKEY_ApplicationRight "ApplicationRight"
#define LAXKEY_Book             "Book"
#define LAXKEY_CD               "CD"
#define LAXKEY_Calculater       "Calculater"
#define LAXKEY_Clear            "Clear"
#define LAXKEY_Close            "Close"
#define LAXKEY_Copy             "Copy"
#define LAXKEY_Cut              "Cut"
#define LAXKEY_Display          "Display"
#define LAXKEY_DOS              "DOS"
#define LAXKEY_Documents        "Documents"
#define LAXKEY_Excel            "Excel"
#define LAXKEY_Explorer         "Explorer"
#define LAXKEY_Game             "Game"
#define LAXKEY_Go               "Go"
#define LAXKEY_iTouch           "iTouch"
#define LAXKEY_LogOff           "LogOff"
#define LAXKEY_Market           "Market"
#define LAXKEY_Meeting          "Meeting"
#define LAXKEY_MenuKB           "MenuKB"
#define LAXKEY_MenuPB           "MenuPB"
#define LAXKEY_MySites          "MySites"
#define LAXKEY_New              "New"
#define LAXKEY_News             "News"
#define LAXKEY_OfficeHome       "OfficeHome"
#define LAXKEY_Open             "Open"
#define LAXKEY_Option           "Option"
#define LAXKEY_Paste            "Paste"
#define LAXKEY_Phone            "Phone"
#define LAXKEY_Q                "Q"
#define LAXKEY_Reply            "Reply"
#define LAXKEY_Reload           "Reload"
#define LAXKEY_RotateWindows    "RotateWindows"
#define LAXKEY_RotationPB       "RotationPB"
#define LAXKEY_RotationKB       "RotationKB"
#define LAXKEY_Save             "Save"
#define LAXKEY_ScrollUp         "ScrollUp"
#define LAXKEY_ScrollDown       "ScrollDown"
#define LAXKEY_ScrollClick      "ScrollClick"
#define LAXKEY_Send             "Send"
#define LAXKEY_Spell            "Spell"
#define LAXKEY_SplitScreen      "SplitScreen"
#define LAXKEY_Support          "Support"
#define LAXKEY_TaskPane         "TaskPane"
#define LAXKEY_Terminal         "Terminal"
#define LAXKEY_Tools            "Tools"
#define LAXKEY_Travel           "Travel"
#define LAXKEY_UserPB           "UserPB"
#define LAXKEY_User1KB          "User1KB"
#define LAXKEY_User2KB          "User2KB"
#define LAXKEY_Video            "Video"
#define LAXKEY_WheelButton      "WheelButton"
#define LAXKEY_Word             "Word"
#define LAXKEY_Xfer             "Xfer"
#define LAXKEY_ZoomIn           "ZoomIn"
#define LAXKEY_ZoomOut          "ZoomOut"

#define LAXKEY_Away             "Away"
#define LAXKEY_Messenger        "Messenger"
#define LAXKEY_WebCam           "WebCam"
#define LAXKEY_MailForward      "MailForward"
#define LAXKEY_Pictures         "Pictures"
#define LAXKEY_Music            "Music"

#define LAXKEY_Battery          "Battery"
#define LAXKEY_Bluetooth        "Bluetooth"
#define LAXKEY_WLAN             "WLAN"
#define LAXKEY_UWB              "UWB"

#define LAXKEY_AudioForward     "AudioForward"
#define LAXKEY_AudioRepeat      "AudioRepeat"
#define LAXKEY_AudioRandomPlay  "AudioRandomPlay"
#define LAXKEY_Subtitle         "Subtitle"
#define LAXKEY_AudioCycleTrack  "AudioCycleTrack"
#define LAXKEY_CycleAngle       "CycleAngle"
#define LAXKEY_FrameBack        "FrameBack"
#define LAXKEY_FrameForward     "FrameForward"
#define LAXKEY_Time             "Time"
#define LAXKEY_Select           "Select"
#define LAXKEY_View             "View"
#define LAXKEY_TopMenu          "TopMenu"

#define LAXKEY_Red              "Red"
#define LAXKEY_Green            "Green"
#define LAXKEY_Yellow           "Yellow"
#define LAXKEY_Blue             "Blue"

#define LAXKEY_Suspend          "Suspend"
#define LAXKEY_Hibernate        "Hibernate"
#define LAXKEY_TouchpadToggle   "TouchpadToggle"
#define LAXKEY_TouchpadOn       "TouchpadOn"
#define LAXKEY_TouchpadOff      "TouchpadOff"

/* Keys for special action keys (hot keys) */
/* Virtual terminals on some operating systems */
#define LAXKEY_Switch_VT_1      "Switch_VT_1"
#define LAXKEY_Switch_VT_2      "Switch_VT_2"
#define LAXKEY_Switch_VT_3      "Switch_VT_3"
#define LAXKEY_Switch_VT_4      "Switch_VT_4"
#define LAXKEY_Switch_VT_5      "Switch_VT_5"
#define LAXKEY_Switch_VT_6      "Switch_VT_6"
#define LAXKEY_Switch_VT_7      "Switch_VT_7"
#define LAXKEY_Switch_VT_8      "Switch_VT_8"
#define LAXKEY_Switch_VT_9      "Switch_VT_9"
#define LAXKEY_Switch_VT_10     "Switch_VT_10"
#define LAXKEY_Switch_VT_11     "Switch_VT_11"
#define LAXKEY_Switch_VT_12     "Switch_VT_12"

#define LAXKEY_Ungrab           "Ungrab"
#define LAXKEY_ClearGrab        "ClearGrab"
#define LAXKEY_Next_VMode       "Next_VMode"
#define LAXKEY_Prev_VMode       "Prev_VMode"
#define LAXKEY_LogWindowTree    "LogWindowTree"
#define LAXKEY_LogGrabInfo      "LogGrabInfo"
