.TH LAXKIT 1 "$Date: 2011-12-03 18:09:51 -0800 (Sat, 03 Dec 2011) $"
.SH NAME
Laxkit \- Version 0.0.8.1
.br
.SH DESCRIPTION
The Laxkit is a C++ window toolkit currently only for X.

The Laxkit provides a core windowing system,
with common window controls, like scrollbars, text edits, and
the like, and also several interfaces
for manipulating, loading, and saving various art related objects,
particularly vector graphics objects like gradients, bezier patch 
gradients, image distortions, and paths.

The kit is still rather rough, but at least 1 out of 6.5 billion
people is already using it for applications that he uses in the
field. In other words, it is being used as the backbone for
Laidout (http://www.laidout.org), a desktop publishing program.

Please check http://laxkit.sourceforge.net for information
about various bugs and deficiencies of the Laxkit.
Only you can help stop bugs.
 
Donations are encouraged! Money, that is, not bugs.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH DOCUMENTATION
.br
This kit is documented by the doxygen documention found in the source.
.SH COPYRIGHT
This program is released under the LGPL v2.
.SH AUTHOR
\fBLaxkit\fP was written with varying degrees of success by 
\fBTom Lechner\fP <tom@tomlechner.com>,
who is still currently the only developer, and who would probably rather be
drawing cartoons (http://www.tomlechner.com).

